 CREATE TABLE STUDENT(
	STUDENTID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(45) NOT NULL,
	LASTNAME VARCHAR(45) NOT NULL,
	YEARLEVEL INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (`STUDENTID`)
 )
 ENGINE = INNODB;